argo-workflows:
  crds:
    keep: false
  server:
    secure: true
    extraArgs:
    - --auth-mode=server
    - --insecure-skip-verify
  workflow:
    serviceAccount:
      create: true
    rbac:
      create: true