crds:
  keep: false
server:
  secure: true
  extraArgs:
  - --auth-mode=server
  # - --auth-mode=sso
  # - --auth-mode=client
  - --insecure-skip-verify
workflow:
  serviceAccount:
    create: true
  rbac:
    create: true