apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: process-bak-files
  annotations:
    workflows.argoproj.io/description: |
      workflow needs to download all *.bak files
      from s3 bucket on 1 machine. then, sleep and finally 
      upload files to another s3 bucket
spec:
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: task-pv-claim
  entrypoint: main
  onExit: cleanFS
  templates:
  - name: main
    steps:
      - - name: one
          template: download-bak-files
      - - name: two
          template: sleep
      - - name: three
          template: upload-bak-files
  
  - name: download-bak-files
    container:
      image: amazon/aws-cli:latest
      args: [s3, sync, s3://inputzzz, /mnt/vol/]
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-s3-creds
            key: accessKey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-s3-creds
            key: secretKey
      - name: AWS_DEFAULT_REGION
        valueFrom:
          secretKeyRef:
            name: aws-s3-creds
            key: region
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol

  - name: sleep
    container:
      image: alpine:latest
      command: [sh, -c]
      args: [ls -l /mnt/vol && sleep 60 && echo "Done sleeping!! Moving on"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
  
  - name: upload-bak-files
    container:
      image: amazon/aws-cli:latest
      args: [s3, sync, /mnt/vol/, s3://outputzzz]
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-s3-creds
            key: accessKey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-s3-creds
            key: secretKey
      - name: AWS_DEFAULT_REGION
        valueFrom:
          secretKeyRef:
            name: aws-s3-creds
            key: region
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
  
  - name: cleanFS
    container:
      image: alpine:latest
      command: [sh, -c]
      args: [rm -rf /mnt/vol/* && echo "Deleted files from volume"]
      volumeMounts:
      - name: workdir
        mountPath: /mnt/vol
